apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_DB
        - name: MONGO_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_COLLECTION
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI
