apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
      - name: express-frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: FLASK_BACKEND
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_BACKEND
