apiVersion: v1
kind: Service
metadata:
  name: express-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: express-frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: {{ .Values.frontend.nodePort }}
  type: NodePort
